"""annon_id_added_to_SaasSession_model

Revision ID: 4f822856bef9
Revises: 7e33cae9d741
Create Date: 2026-06-09 18:08:07.827241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f822856bef9'
down_revision: Union[str, Sequence[str], None] = '7e33cae9d741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saas_sessions', sa.Column('anon_id', sa.String(length=64), nullable=True))
    op.create_index('ix_saas_session_lookup', 'saas_sessions', ['tenant_id', 'product_id', 'anon_id'], unique=False)
    op.create_index(op.f('ix_saas_sessions_anon_id'), 'saas_sessions', ['anon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saas_sessions_anon_id'), table_name='saas_sessions')
    op.drop_index('ix_saas_session_lookup', table_name='saas_sessions')
    op.drop_column('saas_sessions', 'anon_id')
    # ### end Alembic commands ###
