"""added_webhok_secret_field_to_Tenant_model

Revision ID: 7e33cae9d741
Revises: c844c1a85383
Create Date: 2026-05-24 18:47:16.155305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e33cae9d741'
down_revision: Union[str, Sequence[str], None] = 'c844c1a85383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('transcript_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_logs_id'), 'analytics_logs', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_logs_session_id'), 'analytics_logs', ['session_id'], unique=True)
    op.add_column('tenants', sa.Column('webhook_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'webhook_secret')
    op.drop_index(op.f('ix_analytics_logs_session_id'), table_name='analytics_logs')
    op.drop_index(op.f('ix_analytics_logs_id'), table_name='analytics_logs')
    op.drop_table('analytics_logs')
    # ### end Alembic commands ###
