"""add negotiation_outcomes table

Revision ID: cd0c8790ef68
Revises: b10e2ae52a91
Create Date: 2026-04-25 18:56:02.839545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0c8790ef68'
down_revision: Union[str, Sequence[str], None] = 'b10e2ae52a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('asking_price', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.Column('user_language', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_outcomes_id'), 'negotiation_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_negotiation_outcomes_session_id'), 'negotiation_outcomes', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_outcomes_session_id'), table_name='negotiation_outcomes')
    op.drop_index(op.f('ix_negotiation_outcomes_id'), table_name='negotiation_outcomes')
    op.drop_table('negotiation_outcomes')
    # ### end Alembic commands ###
